// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevenueRecognitionSystem.Infrastructure.Data;

#nullable disable

namespace RevenueRecognitionSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202200916_AddSoftwareSystem11")]
    partial class AddSoftwareSystem11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);

                    b.HasDiscriminator<string>("ClientType").IsComplete(true).HasValue("Client");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.SoftwareSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<decimal?>("MonthlySubscriptionPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("UpfrontPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.ToTable("SoftwareSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            CurrentVersion = "1.2.3",
                            Description = "Financial software",
                            IdClient = 1,
                            MonthlySubscriptionPrice = 29.99m,
                            Name = "FinTrack",
                            UpfrontPrice = 499.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            CurrentVersion = "3.0.0",
                            Description = "Education platform",
                            IdClient = 4,
                            MonthlySubscriptionPrice = 19.99m,
                            Name = "LearnMate"
                        });
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Company", b =>
                {
                    b.HasBaseType("RevenueRecognitionSystem.Domain.Entities.Client");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KRSNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasDiscriminator().HasValue("Company");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Address = "Gdansk, ul. Portowa 12",
                            Email = "info@techsoft.com",
                            PhoneNumber = "111222333",
                            CompanyName = "TechSoft Ltd.",
                            KRSNumber = "0000123456"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Poznan, ul. Edukacyjna 7",
                            Email = "contact@educorp.com",
                            PhoneNumber = "444555666",
                            CompanyName = "EduCorp Sp. z o.o.",
                            KRSNumber = "0000654321"
                        });
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Individual", b =>
                {
                    b.HasBaseType("RevenueRecognitionSystem.Domain.Entities.Client");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasDiscriminator().HasValue("Individual");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Address = "Warsaw, ul. Centralna 10",
                            Email = "jan.kowalski@example.com",
                            PhoneNumber = "123456789",
                            FirstName = "Jan",
                            IsDeleted = false,
                            LastName = "Kowalski",
                            PESEL = "90010112345"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Krakow, ul. Zielona 5",
                            Email = "anna.nowak@example.com",
                            PhoneNumber = "987654321",
                            FirstName = "Anna",
                            IsDeleted = false,
                            LastName = "Nowak",
                            PESEL = "85050567890"
                        });
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.SoftwareSystem", b =>
                {
                    b.HasOne("RevenueRecognitionSystem.Domain.Entities.Client", "Client")
                        .WithMany("SoftwareSystems")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Client", b =>
                {
                    b.Navigation("SoftwareSystems");
                });
#pragma warning restore 612, 618
        }
    }
}
