// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevenueRecognitionSystem.Infrastructure.Data;

#nullable disable

namespace RevenueRecognitionSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);

                    b.HasDiscriminator<string>("ClientType").IsComplete(true).HasValue("Client");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoftwareSystemId")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UpdateYears")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareSystemId");

                    b.ToTable("Contracts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 2, 27, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1800),
                            EndDate = new DateTime(2026, 3, 9, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1867),
                            IsCancelled = false,
                            IsPaid = true,
                            Price = 4500m,
                            SoftwareSystemId = 1,
                            SoftwareVersion = "1.0",
                            StartDate = new DateTime(2026, 2, 27, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1863),
                            UpdateYears = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CreatedAt = new DateTime(2026, 2, 27, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1876),
                            EndDate = new DateTime(2046, 2, 27, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1880),
                            IsCancelled = false,
                            IsPaid = true,
                            Price = 6000m,
                            SoftwareSystemId = 2,
                            SoftwareVersion = "2.1",
                            StartDate = new DateTime(2026, 2, 27, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1878),
                            UpdateYears = 2
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            CreatedAt = new DateTime(2026, 2, 27, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1889),
                            EndDate = new DateTime(2036, 2, 27, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1892),
                            IsCancelled = false,
                            IsPaid = true,
                            Price = 8500m,
                            SoftwareSystemId = 3,
                            SoftwareVersion = "3.2",
                            StartDate = new DateTime(2026, 2, 27, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1891),
                            UpdateYears = 1
                        });
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoftwareSystemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Target")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareSystemId");

                    b.ToTable("Discounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New Year",
                            Percentage = 10m,
                            SoftwareSystemId = 1,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target = 2
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spring Sale",
                            Percentage = 15m,
                            SoftwareSystemId = 2,
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target = 2
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Health Promo",
                            Percentage = 5m,
                            SoftwareSystemId = 3,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target = 2
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Summer Deal",
                            Percentage = 20m,
                            SoftwareSystemId = 4,
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target = 2
                        },
                        new
                        {
                            Id = 5,
                            EndDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Autumn Deal",
                            Percentage = 12m,
                            SoftwareSystemId = 5,
                            StartDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target = 2
                        },
                        new
                        {
                            Id = 6,
                            EndDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cloud Discount",
                            Percentage = 18m,
                            SoftwareSystemId = 6,
                            StartDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target = 2
                        },
                        new
                        {
                            Id = 7,
                            EndDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Logistics Promo",
                            Percentage = 8m,
                            SoftwareSystemId = 7,
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target = 2
                        },
                        new
                        {
                            Id = 8,
                            EndDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Auto Deal",
                            Percentage = 7m,
                            SoftwareSystemId = 8,
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target = 2
                        },
                        new
                        {
                            Id = 9,
                            EndDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HR Promo",
                            Percentage = 6m,
                            SoftwareSystemId = 9,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target = 2
                        },
                        new
                        {
                            Id = 10,
                            EndDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Security Week",
                            Percentage = 25m,
                            SoftwareSystemId = 10,
                            StartDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target = 2
                        });
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExp")
                        .HasColumnType("datetime");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.SoftwareSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("OneYearLicensePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SoftwareSystems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            CurrentVersion = "1.0",
                            Description = "Finance System",
                            Name = "FinTrack",
                            OneYearLicensePrice = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            CurrentVersion = "2.1",
                            Description = "Education Platform",
                            Name = "EduPro",
                            OneYearLicensePrice = 7000m
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            CurrentVersion = "3.2",
                            Description = "Medical System",
                            Name = "HealthCareX",
                            OneYearLicensePrice = 9000m
                        },
                        new
                        {
                            Id = 4,
                            Category = 4,
                            CurrentVersion = "1.4",
                            Description = "Construction Management",
                            Name = "BuildMaster",
                            OneYearLicensePrice = 8000m
                        },
                        new
                        {
                            Id = 5,
                            Category = 4,
                            CurrentVersion = "5.0",
                            Description = "Retail Software",
                            Name = "RetailSuite",
                            OneYearLicensePrice = 6500m
                        },
                        new
                        {
                            Id = 6,
                            Category = 4,
                            CurrentVersion = "4.0",
                            Description = "Cloud Platform",
                            Name = "CloudBase",
                            OneYearLicensePrice = 12000m
                        },
                        new
                        {
                            Id = 7,
                            Category = 4,
                            CurrentVersion = "2.5",
                            Description = "Logistics System",
                            Name = "LogiTrack",
                            OneYearLicensePrice = 7500m
                        },
                        new
                        {
                            Id = 8,
                            Category = 4,
                            CurrentVersion = "3.1",
                            Description = "Automotive Software",
                            Name = "AutoManager",
                            OneYearLicensePrice = 6000m
                        },
                        new
                        {
                            Id = 9,
                            Category = 4,
                            CurrentVersion = "6.2",
                            Description = "HR Management",
                            Name = "HRPro",
                            OneYearLicensePrice = 5500m
                        },
                        new
                        {
                            Id = 10,
                            Category = 4,
                            CurrentVersion = "1.8",
                            Description = "Security System",
                            Name = "SecureIT",
                            OneYearLicensePrice = 10000m
                        });
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RenewalPeriodInMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("RenewalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoftwareSystemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareSystemId");

                    b.ToTable("Subscriptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            IsCancelled = true,
                            Name = "Monthly Subscription",
                            RenewalPeriodInMonths = 1,
                            RenewalPrice = 900m,
                            SoftwareSystemId = 1,
                            StartDate = new DateTime(2026, 2, 27, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1924)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            IsCancelled = true,
                            Name = "Monthly Subscription",
                            RenewalPeriodInMonths = 1,
                            RenewalPrice = 1200m,
                            SoftwareSystemId = 2,
                            StartDate = new DateTime(2026, 2, 27, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1929)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            IsCancelled = true,
                            Name = "2 Years Subscription",
                            RenewalPeriodInMonths = 24,
                            RenewalPrice = 8000m,
                            SoftwareSystemId = 3,
                            StartDate = new DateTime(2026, 2, 27, 16, 3, 52, 930, DateTimeKind.Local).AddTicks(1934)
                        });
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionPayments", (string)null);
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Company", b =>
                {
                    b.HasBaseType("RevenueRecognitionSystem.Domain.Entities.Client");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KRSNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasDiscriminator().HasValue("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Gdansk 1",
                            ClientType = "Company",
                            Email = "c1@comp.pl",
                            PhoneNumber = "111111111",
                            CompanyName = "TechSoft",
                            KRSNumber = "0000000001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gdansk 2",
                            ClientType = "Company",
                            Email = "c2@comp.pl",
                            PhoneNumber = "111111112",
                            CompanyName = "EduCorp",
                            KRSNumber = "0000000002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Gdynia 3",
                            ClientType = "Company",
                            Email = "c3@comp.pl",
                            PhoneNumber = "111111113",
                            CompanyName = "FinGroup",
                            KRSNumber = "0000000003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Warsaw 4",
                            ClientType = "Company",
                            Email = "c4@comp.pl",
                            PhoneNumber = "111111114",
                            CompanyName = "MedTech",
                            KRSNumber = "0000000004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Poznan 5",
                            ClientType = "Company",
                            Email = "c5@comp.pl",
                            PhoneNumber = "111111115",
                            CompanyName = "BuildIT",
                            KRSNumber = "0000000005"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Krakow 6",
                            ClientType = "Company",
                            Email = "c6@comp.pl",
                            PhoneNumber = "111111116",
                            CompanyName = "LogiSoft",
                            KRSNumber = "0000000006"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Lodz 7",
                            ClientType = "Company",
                            Email = "c7@comp.pl",
                            PhoneNumber = "111111117",
                            CompanyName = "HealthPlus",
                            KRSNumber = "0000000007"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Wroclaw 8",
                            ClientType = "Company",
                            Email = "c8@comp.pl",
                            PhoneNumber = "111111118",
                            CompanyName = "CloudNet",
                            KRSNumber = "0000000008"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Sopot 9",
                            ClientType = "Company",
                            Email = "c9@comp.pl",
                            PhoneNumber = "111111119",
                            CompanyName = "RetailPro",
                            KRSNumber = "0000000009"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Katowice 10",
                            ClientType = "Company",
                            Email = "c10@comp.pl",
                            PhoneNumber = "111111120",
                            CompanyName = "AutoSys",
                            KRSNumber = "0000000010"
                        });
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Individual", b =>
                {
                    b.HasBaseType("RevenueRecognitionSystem.Domain.Entities.Client");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasDiscriminator().HasValue("Individual");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Address = "Warsaw A",
                            ClientType = "Individual",
                            Email = "i1@mail.pl",
                            PhoneNumber = "222222221",
                            FirstName = "Jan",
                            IsDeleted = false,
                            LastName = "Kowalski",
                            PESEL = "90010100001"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Warsaw B",
                            ClientType = "Individual",
                            Email = "i2@mail.pl",
                            PhoneNumber = "222222222",
                            FirstName = "Anna",
                            IsDeleted = false,
                            LastName = "Nowak",
                            PESEL = "90010100002"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Krakow C",
                            ClientType = "Individual",
                            Email = "i3@mail.pl",
                            PhoneNumber = "222222223",
                            FirstName = "Piotr",
                            IsDeleted = false,
                            LastName = "Zielinski",
                            PESEL = "90010100003"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Lodz D",
                            ClientType = "Individual",
                            Email = "i4@mail.pl",
                            PhoneNumber = "222222224",
                            FirstName = "Maria",
                            IsDeleted = false,
                            LastName = "Wojcik",
                            PESEL = "90010100004"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Gdansk E",
                            ClientType = "Individual",
                            Email = "i5@mail.pl",
                            PhoneNumber = "222222225",
                            FirstName = "Tomasz",
                            IsDeleted = false,
                            LastName = "Lewandowski",
                            PESEL = "90010100005"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Poznan F",
                            ClientType = "Individual",
                            Email = "i6@mail.pl",
                            PhoneNumber = "222222226",
                            FirstName = "Kasia",
                            IsDeleted = false,
                            LastName = "Kaminska",
                            PESEL = "90010100006"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Wroclaw G",
                            ClientType = "Individual",
                            Email = "i7@mail.pl",
                            PhoneNumber = "222222227",
                            FirstName = "Marek",
                            IsDeleted = false,
                            LastName = "Kaczmarek",
                            PESEL = "90010100007"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Szczecin H",
                            ClientType = "Individual",
                            Email = "i8@mail.pl",
                            PhoneNumber = "222222228",
                            FirstName = "Ewa",
                            IsDeleted = false,
                            LastName = "Mazur",
                            PESEL = "90010100008"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Lublin I",
                            ClientType = "Individual",
                            Email = "i9@mail.pl",
                            PhoneNumber = "222222229",
                            FirstName = "Adam",
                            IsDeleted = false,
                            LastName = "Krol",
                            PESEL = "90010100009"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Rzeszow J",
                            ClientType = "Individual",
                            Email = "i10@mail.pl",
                            PhoneNumber = "222222230",
                            FirstName = "Olga",
                            IsDeleted = false,
                            LastName = "Dabrowska",
                            PESEL = "90010100010"
                        });
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Contract", b =>
                {
                    b.HasOne("RevenueRecognitionSystem.Domain.Entities.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevenueRecognitionSystem.Domain.Entities.SoftwareSystem", "SoftwareSystem")
                        .WithMany("Contracts")
                        .HasForeignKey("SoftwareSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SoftwareSystem");
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Discount", b =>
                {
                    b.HasOne("RevenueRecognitionSystem.Domain.Entities.SoftwareSystem", "SoftwareSystem")
                        .WithMany("Discounts")
                        .HasForeignKey("SoftwareSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareSystem");
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Payment", b =>
                {
                    b.HasOne("RevenueRecognitionSystem.Domain.Entities.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("RevenueRecognitionSystem.Domain.Entities.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevenueRecognitionSystem.Domain.Entities.SoftwareSystem", "SoftwareSystem")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SoftwareSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SoftwareSystem");
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.HasOne("RevenueRecognitionSystem.Domain.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Client", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.SoftwareSystem", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Discounts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("RevenueRecognitionSystem.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("SubscriptionPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
