<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Contracts\Responses\" />
      <Folder Include="Implementations\" />
      <Folder Include="Interfaces\" />
      <Folder Include="Validators\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RevenueRecognitionSystem.Domain\RevenueRecognitionSystem.Domain.csproj" />
    </ItemGroup>

</Project>
